# Generated by Django 4.1.5 on 2023-01-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_estudiante_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='camada',
            new_name='apellido',
        ),
    ]
