# Generated by Django 4.1.5 on 2023-01-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_camada_profesor_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='progesion',
            new_name='profesion',
        ),
    ]
