# Generated by Django 4.1.5 on 2023-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='cusros',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
    ]
