# Generated by Django 4.1.5 on 2023-01-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0007_profesor_cusros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-nombre', 'camada'], 'verbose_name': 'Cours', 'verbose_name_plural': 'My Courese'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cusros',
            field=models.ManyToManyField(related_name='profesor_curso', to='AppCoder.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'camada')},
        ),
    ]
